import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faBars,
  faTimes,
  faPuzzlePiece,
  faCircle,
  faChevronDown,
  faChevronRight,
  faLightbulb,
  faBell,
  faFlagCheckered,
  faFloppyDisk,
  faBorderAll,
  faClipboardQuestion,
  faClockFour,
  faHeadset,
  faPause,
  faGamepad,
} from '@fortawesome/free-solid-svg-icons';

export {
  FontAwesomeIcon,
  faBars,
  faTimes,
  faPuzzlePiece,
  faCircle,
  faChevronDown,
  faChevronRight,
  faLightbulb,
  faBell,
  faFlagCheckered,
  faFloppyDisk,
  faBorderAll,
  faClipboardQuestion,
  faClockFour,
  faHeadset,
  faPause,
  faGamepad,
};
